services:
  app:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    container_name: forgebase_app
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - forgebase

  web:
    image: nginx:latest
    container_name: forgebase_web
    ports:
      - "80:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - forgebase

  db:
    image: postgres:15
    container_name: forgebase_db
    environment:
      POSTGRES_DB: forgebase
      POSTGRES_USER: forgebase
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    networks:
      - forgebase

  redis:
    image: redis:latest
    container_name: forgebase_redis
    networks:
      - forgebase

  node:
    image: node:20-alpine
    container_name: forgebase_node
    working_dir: /var/www
    volumes:
      - .:/var/www
    command: sh -c "sleep infinity"
    networks:
      - forgebase

networks:
  forgebase:
